# Introduction to Tensors

https://www.tensorflow.org/guide/basics

### **Chapter 1**

What Tensors are

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.3.0


In [3]:
# creating tensors withtf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [5]:
#Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
#Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
#Create a matrix with specified datatype
matrix2 = tf.constant([[12.3,13.9,2.7], 
                        [-32.8, 65.2, -1.09],
                        [9.8,-7.2,0.07],
                        [9.,0.34,-45.9]], dtype=tf.float32)
matrix2

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 12.3 ,  13.9 ,   2.7 ],
       [-32.8 ,  65.2 ,  -1.09],
       [  9.8 ,  -7.2 ,   0.07],
       [  9.  ,   0.34, -45.9 ]], dtype=float32)>

In [10]:
matrix2.ndim

2

In [11]:
# Create a tensor
tensor = tf.constant([[[1,2,3,10],
                        [4,5,6,20]],
                      [[8,-2,4,30],
                        [5,-3,2,40]],
                        [[12,3,4,50],
                        [5,1,4,60]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3, 10],
        [ 4,  5,  6, 20]],

       [[ 8, -2,  4, 30],
        [ 5, -3,  2, 40]],

       [[12,  3,  4, 50],
        [ 5,  1,  4, 60]]])>

In [12]:
tensor.ndim

3

**Summary:**

* **Scalar:** is a single number <br>
* **Vectro:** is a number with direction (speed and direction)<br>
* **Matrix:** is a 2-d array of numbers<br>
* **Tensor:** is a n-d array of numbers (n = 0 to ...)

### **Chapter 2**

Creating tensors with TensorFlow

In [13]:
#Create the same tensors with tf.variable()
changeable_vector = tf.Variable([10,10])
unchangeable_vector = tf.constant([10,10])
changeable_vector, unchangeable_vector

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>)

In [14]:
changeable_vector[0].assign(7)
changeable_vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

In [15]:
#unchangeable_vector[0].assign(7) #AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

a default tensor created with tf.constant() is a inmutable array of numbers, which all are from the same data type

**randomized tensors:** <br>
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [16]:
random_0 = tf.random.Generator.from_seed(42)
random_0 = random_0.normal(shape=[2])
random_0.numpy()

array([-0.7565803 , -0.06854702], dtype=float32)

In [17]:
#random_0[0].assign(7) 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [18]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,4,2,1), mean=12.3, stddev=3.2, dtype=tf.dtypes.float32)
random_3

<tf.Tensor: shape=(3, 4, 2, 1), dtype=float32, numpy=
array([[[[ 9.878943 ],
         [12.080649 ]],

        [[12.543041 ],
         [ 8.27637  ]],

        [[11.557799 ],
         [ 6.5054865]],

        [[12.619639 ],
         [10.668043 ]]],


       [[[ 9.888542 ],
         [10.470679 ]],

        [[12.773848 ],
         [11.552384 ]],

        [[11.172706 ],
         [13.59988  ]],

        [[ 8.932477 ],
         [16.15747  ]]],


       [[[17.699837 ],
         [10.871848 ]],

        [[ 4.8085303],
         [15.468291 ]],

        [[12.019577 ],
         [10.266182 ]],

        [[10.328244 ],
         [ 6.078731 ]]]], dtype=float32)>

In [21]:
# creates new values every time the cell is run

print(tf.random.uniform([1])) #tf.Tensor([0.9236865], shape=(1,), dtype=float32)
print(tf.random.uniform([1])) #tf.Tensor([0.88400424], shape=(1,), dtype=float32)
print(tf.random.uniform([1])) #tf.Tensor([0.32772207], shape=(1,), dtype=float32)

tf.Tensor([0.28488898], shape=(1,), dtype=float32)
tf.Tensor([0.76416767], shape=(1,), dtype=float32)
tf.Tensor([0.51159513], shape=(1,), dtype=float32)


In [22]:
# creates new values every time the cell is run but always the same

print(tf.random.uniform([1], seed= 42)) 
print(tf.random.uniform([1], seed= 42)) 
print(tf.random.uniform([1], seed= 42)) 


# first execution
# tf.Tensor([0.95227146], shape=(1,), dtype=float32)
# tf.Tensor([0.8960779], shape=(1,), dtype=float32)
# tf.Tensor([0.70954347], shape=(1,), dtype=float32)


# second execution
# tf.Tensor([0.18126988], shape=(1,), dtype=float32)
# tf.Tensor([0.06347668], shape=(1,), dtype=float32)
# tf.Tensor([0.81274223], shape=(1,), dtype=float32)

# third execution
# tf.Tensor([0.15116918], shape=(1,), dtype=float32)
# tf.Tensor([0.5001906], shape=(1,), dtype=float32)
# tf.Tensor([0.88570464], shape=(1,), dtype=float32)

tf.Tensor([0.95227146], shape=(1,), dtype=float32)
tf.Tensor([0.8960779], shape=(1,), dtype=float32)
tf.Tensor([0.70954347], shape=(1,), dtype=float32)


generating pseudo random numbers is important to rerun experiments, because it gives control which parameters a fixed and which are changed <br>
for this global random state is created with tf.random.set_seet(*integer*)

In [23]:
tf.random.set_seed(42)
print(tf.random.uniform([1])) #tf.Tensor([0.6645621], shape=(1,), dtype=float32)
print(tf.random.uniform([1])) #tf.Tensor([0.68789124], shape=(1,), dtype=float32)
print(tf.random.uniform([1])) #tf.Tensor([0.7413678], shape=(1,), dtype=float32)

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [24]:
tf.random.set_seed(42)
print(tf.random.uniform([1])) #tf.Tensor([0.6645621], shape=(1,), dtype=float32)
print(tf.random.uniform([1])) #tf.Tensor([0.68789124], shape=(1,), dtype=float32)
print(tf.random.uniform([1])) #tf.Tensor([0.7413678], shape=(1,), dtype=float32)

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [25]:
tf.random.set_seed(42)
print(tf.random.uniform([1], seed= 42)) #tf.Tensor([0.4163028], shape=(1,), dtype=float32)
print(tf.random.uniform([1], seed= 42)) #tf.Tensor([0.0332247], shape=(1,), dtype=float32)
print(tf.random.uniform([1], seed= 42)) #tf.Tensor([0.16061568], shape=(1,), dtype=float32)

tf.Tensor([0.4163028], shape=(1,), dtype=float32)
tf.Tensor([0.0332247], shape=(1,), dtype=float32)
tf.Tensor([0.16061568], shape=(1,), dtype=float32)


**Summary:** <br>
Creating tensors with tf.constant or with <br>
 aTensor = tf.random.Generator.from_seed(42) and aTensor = aTensor.normal(shape=(3,2)) <br>
 .normal specifies the stochastic distribution <br>
 * Global seed (tf.random.set.seed()) produces the same values whenever the cell is rerun!
 * Operational seed (or unset seed) produces new values whenever the cell is rerun!

### **Chapter 3**

shuffling the order of tensor elements along the first axis ( = the rows of a matrix) is valuable for shuffling data

In [26]:
not_shuffled = tf.constant([[10,7],
                            [2,3],
                              [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 5,  6]])>

In [27]:
shuffled = tf.random.shuffle(value=not_shuffled) #shuffles along its first dimension
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 5,  6],
       [10,  7]])>

In [28]:
shuffled2 = tf.random.shuffle(value=not_shuffled[0:3:2])
shuffled2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]])>

### Chapter 4

Creating special tesnors and getting information about tensors

In [29]:
#create a tesnor all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
#create a tensor all zeros
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [31]:
# numpy arrays to tensors
# the main difference between np-array and tensors is, tensors are optimized for running on GPUs
import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [32]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

In [33]:
numpy_A.reshape((2,3,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [34]:
#Getting information from tensors

# Shape
# Rank
# Axis or dimension
# size

In [35]:
rank_4_tensors = tf.zeros(shape=(2,3,4,5))
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensors[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [37]:
rank_4_tensors[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [38]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors), tf.rank(rank_4_tensors)

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [39]:
# Get various attributes of a´´our tensors
print('Datatype of every element: ', rank_4_tensors.dtype)
print('Number of dimensions ( .ndim): ', rank_4_tensors.ndim)
print('Shape of a tensor ( .shape): ', rank_4_tensors.shape)
print('Elements along the first axis (): ', rank_4_tensors.shape[0])
print('Elements along the last axis (): ', rank_4_tensors.shape[-1])
print('Number of dimension (tf.rank()): ', tf.rank(rank_4_tensors).numpy())
print('Size of a tensor (tf.size()): ', tf.size(rank_4_tensors).numpy()) # .numpy() formats the output in a more readable way
print('Size of a tensor (tf.size()): ', tf.size(rank_4_tensors))

Datatype of every element:  <dtype: 'float32'>
Number of dimensions ( .ndim):  4
Shape of a tensor ( .shape):  (2, 3, 4, 5)
Elements along the first axis ():  2
Elements along the last axis ():  5
Number of dimension (tf.rank()):  4
Size of a tensor (tf.size()):  120
Size of a tensor (tf.size()):  tf.Tensor(120, shape=(), dtype=int32)


### Chapter 5

indexing elements of a tensor is similar to python lists

In [40]:

r4tensor = tf.constant(np.arange(1,121), shape=(2,3,4,5))
print(r4tensor[:1, :1, :1, :1].numpy())
print('----------------')
print(r4tensor[:2, :1, :1, :1].numpy())
print('----------------')
print(r4tensor[:1, :2, :1, :1].numpy())
print('----------------')
print(r4tensor[:1, :1, :2, :1].numpy())
print('----------------')
print(r4tensor[:1, :1, :1, :2].numpy())

[[[[1]]]]
----------------
[[[[ 1]]]


 [[[61]]]]
----------------
[[[[ 1]]

  [[21]]]]
----------------
[[[[1]
   [6]]]]
----------------
[[[[1 2]]]]


In [41]:
# get the first element from each dimension from each index except the final one
print(r4tensor[:1, :1, :1, :].numpy())
print(r4tensor[0,0,0,:].numpy())

[[[[1 2 3 4 5]]]]
[1 2 3 4 5]


In [42]:
# get the first element from each dimension from each index except the second last one
print(r4tensor[:1, :1, :, :1].numpy())
print(r4tensor[0,0,:,0].numpy())

[[[[ 1]
   [ 6]
   [11]
   [16]]]]
[ 1  6 11 16]


In [43]:
# Create a rank 2 tensor
r2tensor = tf.constant([[10,7],
                      [8,9]])
r2tensor.shape, r2tensor.ndim

(TensorShape([2, 2]), 2)

In [44]:
# Get the last item or each row
print(r2tensor[:, -1:].numpy())
print(r2tensor[:,-1].numpy())

[[7]
 [9]]
[7 9]


In [45]:
# Add in extra dimension
r3tensor = r2tensor[..., tf.newaxis] # =  r2tensor[:,: , tf.newaxis]
r3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 8],
        [ 9]]])>

In [46]:
tf.expand_dims(r2tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 8],
        [ 9]]])>

In [47]:
tf.expand_dims(r2tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 8,  9]]])>

In [48]:
tf.expand_dims(r2tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 8,  9]]])>

In [49]:
tf.expand_dims(r2tensor, axis = 2) # =-1

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 8],
        [ 9]]])>

### Chapter 6

Basic operations: <br>
* scalar multiplikation, addition, subtraction, division (aka elementwise)
     * using normal operation notation (* , + , -, /) or tf.math.multiply , .add,  ....
* matrix multiplication
     * with tf.linalg.matmul(tesn1, tens2) or (with limitations) @ (Python)


In [50]:
tensor = tf.constant([[10,7],
                      [2,3]])
tensor + 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [22, 23]])>

In [51]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]])>

In [52]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]])>

In [53]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-8, -7]])>

In [54]:
tensor /6

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.66666667, 1.16666667],
       [0.33333333, 0.5       ]])>

*** using the tensorflow library ***


In [55]:
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]])>

In [56]:
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]])>

**matrix multiplikation**

In [57]:
t1 = tf.constant([[10,7],
                  [4,5]])
t2 = tf.constant([[2,3],
                  [11,6]])

In [58]:
t1 * t2 # elementwise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 21],
       [44, 30]])>

In [59]:
tf.linalg.matmul(t1,t2) # matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[97, 72],
       [63, 42]])>

In [60]:
t1 @ t2 # matrix multiplication with python

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[97, 72],
       [63, 42]])>

In [61]:
t3 = tf.constant([
                [
                [10,7],
                [1,2]
                ],
                [
                [3,4],
                [6,7]
                ]
                ])
t4 = tf.constant([
                [
                [2,4],
                [-1,7]
                ],
                [
                [5,-2],
                [9,2]
                ]
                ])

In [62]:
t3.shape, t4.shape

(TensorShape([2, 2, 2]), TensorShape([2, 2, 2]))

In [63]:
t3*t4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[20, 28],
        [-1, 14]],

       [[15, -8],
        [54, 14]]])>

In [64]:
tf.linalg.matmul(t3,t4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[13, 89],
        [ 0, 18]],

       [[51,  2],
        [93,  2]]])>

In [65]:
tf.linalg.matmul(t3,t4)[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 89],
       [ 0, 18]])>

In [66]:
tf.linalg.matmul(t3,t4)[1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51,  2],
       [93,  2]])>

In [67]:
tf.linalg.matmul(t3,t4)[1][0].numpy()

array([51,  2])

In [68]:
tf.linalg.matmul(t3,t4)[1][0][1].numpy()

2

In [69]:
tf.linalg.matmul(t3,t4)[1:2,:1,1:2].numpy()

array([[[2]]])

In [70]:
tf.linalg.matmul(t3,t4)[1,0,1].numpy()

2

In [71]:
tf.random.set_seed(42)
t5 = tf.random.uniform(shape=(2,2,3)) 
t6 = tf.random.uniform(shape=(2,3,2)) 

In [72]:
#t5 * t6  doesn't work due to dimension mismatch

In [73]:
tf.linalg.matmul(t5, t6)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1.1257328 , 0.74815416],
        [0.85145205, 0.84463745]],

       [[1.0646195 , 1.1898088 ],
        [0.50868213, 0.840804  ]]], dtype=float32)>

In [74]:
t7 = tf.constant([[4,5,6],[7,8,9]])
t7

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]])>

In [75]:
t8= tf.transpose(t7)

In [76]:
tf.matmul(t7,t8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 77, 122],
       [122, 194]])>

In [77]:
tf.matmul(t8,t7)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 65,  76,  87],
       [ 76,  89, 102],
       [ 87, 102, 117]])>

In [78]:
t9 = tf.constant([
                [[2,3,10],[3,4,20]],
                [[5,6,30],[7,8,40]]
                ])
t9

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 2,  3, 10],
        [ 3,  4, 20]],

       [[ 5,  6, 30],
        [ 7,  8, 40]]])>

In [79]:
tf.transpose(t9)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 2,  5],
        [ 3,  7]],

       [[ 3,  6],
        [ 4,  8]],

       [[10, 30],
        [20, 40]]])>

### Chapter 7

tensor.dot <br>
similar to matrix multiplication but gives additional control over axes

In [80]:
t1, t2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 4,  5]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 2,  3],
        [11,  6]])>)

In [81]:
newt = tf.tensordot(t1,t2,axes=0) # creates a new 4dim tensor. Every entry of t1 is scalar-multiplied with t2, where newt[:,:,:,:] = newt[(shape of t1), (shape of t2)]
newt

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 20,  30],
         [110,  60]],

        [[ 14,  21],
         [ 77,  42]]],


       [[[  8,  12],
         [ 44,  24]],

        [[ 10,  15],
         [ 55,  30]]]])>

In [82]:
newt[0,0,:,:] #t1[0,0] * t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 20,  30],
       [110,  60]])>

In [83]:
newt[0,1,:,:] #t1[1,0] * t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 21],
       [77, 42]])>

In [84]:
newt[1,0,:,:] #t1[0,1] * t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 12],
       [44, 24]])>

In [85]:
newt[1,1,:,:] #t1[1,1] * t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 15],
       [55, 30]])>

In [86]:
tf.tensordot(t1,t2,axes=1) # similar to matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[97, 72],
       [63, 42]])>

In [87]:
print(t9.shape)
print(tf.transpose(t9).shape)
print(tf.tensordot(t9,tf.transpose(t9), axes=1).shape)

(2, 2, 3)
(3, 2, 2)
(2, 2, 2, 2)


In [88]:
print(t9.shape)
print(tf.transpose(t9).shape)
print(tf.tensordot(t9,tf.transpose(t9), axes=0).shape)

(2, 2, 3)
(3, 2, 2)
(2, 2, 3, 3, 2, 2)


In [89]:
#tf.matmul(t9,tf.transpose(t9)) dimension mismatch

In [90]:
v1 = tf.constant([1,2])
v2 = tf.constant([[3],[4]])

In [91]:
tf.tensordot(v1,v2, axes=0)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[6],
        [8]]])>

In [92]:
tf.tensordot(v1,v2, axes=1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([11])>

In [93]:
tf.tensordot(v2,v1, axes=0)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[3, 6]],

       [[4, 8]]])>

In [94]:
tf.random.set_seed(101)
t20 = tf.random.uniform(shape=(8,9,10,11))
t21 = tf.random.normal(shape=(1,2,3,4,5,6,7))
print(t20.shape)
print(t21.shape)
print(tf.tensordot(t20,t21, axes=0).shape)
print(tf.tensordot(t21,t20, axes=0).shape)
print(str(tf.size(t20).numpy()) + " = " + str(int(np.math.factorial(11) / np.math.factorial(7))))
print(str(tf.size(t21).numpy()) + " = " + str(np.math.factorial(7)))
print(tf.size(tf.tensordot(t20,t21, axes=0)).numpy())
print(tf.size(tf.tensordot(t21,t20, axes=0)).numpy())
# axes = 1 requires fitting dimensions!!!
#print(tf.tensordot(t20,t21, axes=1).shape)
#print(tf.tensordot(t21,t20, axes=1).shape)

(8, 9, 10, 11)
(1, 2, 3, 4, 5, 6, 7)
(8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
7920 = 7920
5040 = 5040
39916800
39916800


### Chapter 9

tesnors with user defined data types

In [95]:
# Create tensor with default dtype =float32

In [96]:
b = tf.constant([1.7,2.3])
b.dtype

tf.float32

In [97]:
c = tf.constant([1,2])
c.dtype

tf.int32

In [98]:
b = tf.cast(b, dtype= tf.float16)
b.dtype

tf.float16

In [99]:
c = tf.cast(c, dtype=tf.float64)
c

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 2.])>

### Chapter 10

aggregating tensors (certain functions to return information about a tensor)
* tf.abs(t) (absolute value)
* t.shape
* tf.size(t) ( a product of all dimensions)
* tf.reduce_min/max/mean/std(t)

In [100]:
# Aggregating tensors

In [101]:
a = tf.constant([-7,-10])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [102]:
#geting absolute values
tf.abs(a)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [103]:
# random tensor
e = tf.constant(np.random.randint(0,100, size =50))
e.shape, tf.size(e)


(TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [104]:
tf.reduce_min(e).numpy()

5

In [105]:
tf.reduce_max(e).numpy()

98

In [106]:
tf.reduce_mean(e).numpy()

52

In [107]:
tf.reduce_sum(e).numpy()

2610

In [108]:
tf.math.reduce_std(tf.cast(e, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.58>

In [109]:
tf.math.reduce_variance(tf.cast(e, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=816.5>

In [110]:
tf.math.reduce_std(tf.cast(e, dtype=tf.float16))**2


<tf.Tensor: shape=(), dtype=float16, numpy=816.5>

### Finding the positional minimum and maximum 

In [111]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [112]:
# find pos maximum
print(tf.argmax(F).numpy()) # returns the index
print(F[tf.argmax(F)].numpy())
print(tf.reduce_max(F).numpy())

42
0.9671384
0.9671384


In [113]:
# check for equality

F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()

True

In [114]:
# find pos minimum
print(tf.argmin(F).numpy()) # returns the index
print(F[tf.argmin(F)].numpy())
print(tf.reduce_min(F).numpy())

16
0.009463668
0.009463668


In [115]:
tf.random.set_seed(222)
G = tf.random.normal(shape=(2,4))
G

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.8662778 , -1.7805147 ,  1.3079982 , -1.4673755 ],
       [ 0.72068876,  2.2056582 , -0.15544122,  2.539635  ]],
      dtype=float32)>

In [116]:
print(tf.argmax(G, axis = 0))
print(tf.argmax(G, axis = 1))


tf.Tensor([0 1 0 1], shape=(4,), dtype=int64)
tf.Tensor([0 3], shape=(2,), dtype=int64)


In [117]:
tf.random.set_seed(222)
H = tf.random.normal(shape=(2,2,2))
H

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 1.8662778 , -1.7805147 ],
        [ 1.3079982 , -1.4673755 ]],

       [[ 0.72068876,  2.2056582 ],
        [-0.15544122,  2.539635  ]]], dtype=float32)>

In [118]:
print(tf.argmax(H, axis = 0))
print(tf.reduce_max(H, axis =0).numpy())
print("")
print(tf.argmax(H, axis = 1))
print(tf.reduce_max(H, axis =1).numpy())
print("")
print(tf.argmax(H, axis = 2))
print(tf.reduce_max(H, axis =2).numpy())


tf.Tensor(
[[0 1]
 [0 1]], shape=(2, 2), dtype=int64)
[[1.8662778 2.2056582]
 [1.3079982 2.539635 ]]

tf.Tensor(
[[0 1]
 [0 1]], shape=(2, 2), dtype=int64)
[[ 1.8662778  -1.4673755 ]
 [ 0.72068876  2.539635  ]]

tf.Tensor(
[[0 0]
 [1 1]], shape=(2, 2), dtype=int64)
[[1.8662778 1.3079982]
 [2.2056582 2.539635 ]]


### Squeezing a tensor (removing all single diemensions)


In [119]:
tf.random.set_seed(42)
L= tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
L

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [120]:
L.shape

TensorShape([1, 1, 1, 1, 50])

In [121]:
L_squeezed = tf.squeeze(L)
L_squeezed.shape, L_squeezed

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

### Chapter 11

one-hot encoding allows numerical relabeling of categorical values

In [122]:
# Create a list of inices
some_list = [0,1,2,3] # could be red, green, blue, purpel

In [123]:
tf.one_hot(some_list, depth =len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [124]:
# specify custom values for one_hot
tf.one_hot(some_list, depth = len(some_list), on_value='O', off_value=' ')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'O', b' ', b' ', b' '],
       [b' ', b'O', b' ', b' '],
       [b' ', b' ', b'O', b' '],
       [b' ', b' ', b' ', b'O']], dtype=object)>

In [125]:
a_tensor =tf.constant([[0,1,2],[3,4,5]])
a_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [126]:
tf.one_hot(a_tensor, depth = tf.size(a_tensor))

<tf.Tensor: shape=(2, 3, 6), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]], dtype=float32)>

In [127]:
a_tensor2 =tf.constant([[0,1,2],[2,1,0]])
a_tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 1, 0]])>

In [128]:
tf.one_hot(a_tensor2, depth = tf.size(a_tensor))

<tf.Tensor: shape=(2, 3, 6), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.]]], dtype=float32)>

### few more mathematicl operations

In [129]:
#Create a new tensor
J = tf.range(1,10)
J

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [130]:
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [131]:
# tf.sqrt requires floats
tf.math.sqrt(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [132]:
tf.math.log(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [133]:
tf.math.exp(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598152e+01,
       1.4841316e+02, 4.0342880e+02, 1.0966332e+03, 2.9809580e+03,
       8.1030840e+03], dtype=float32)>

In [134]:
tf.random.set_seed(2)
t001= tf.random.normal(shape=(2,2,2))
t001

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 4.3616885e-01, -1.9093795e+00],
        [ 1.3789066e+00, -1.0405852e+00]],

       [[-9.5584162e-04,  1.6947803e-01],
        [ 9.1563100e-01,  5.5124867e-01]]], dtype=float32)>

In [135]:
tf.math.log(tf.abs(t001))

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[-0.82972586,  0.6467783 ],
        [ 0.32129088,  0.03978321]],

       [[-6.9529185 , -1.775032  ],
        [-0.08814184, -0.59556925]]], dtype=float32)>

### Tensors and NumPy

In [136]:
# Create a tensor directly from NumPy array

t002=tf.constant(np.array([[1,2,3],[2,3,4]]))
t002

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]])>

In [137]:
np.array(t002)

array([[1, 2, 3],
       [2, 3, 4]])

In [138]:
t002.numpy()

array([[1, 2, 3],
       [2, 3, 4]])

In [139]:
t002.numpy()[1][1] + 5

8

In [140]:
numpy_K = tf.constant(np.array([3.,7.,10.]))
tensor_K = tf.constant([3.,7.,10.])
numpy_K.dtype, tensor_K.dtype

(tf.float64, tf.float32)

### Chapter 12

TensorFlow on GPUs (requires NVIDIA or a heck of troubleshooting)

In [141]:
### Finding access to GPU
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

if there is acces to a CUDA-enabled GPU, TensorFlow will use it automatically

### Exercise

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [142]:
tens01 = tf.constant([[1,2,3],[4,5,6]])
tens01

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

2. Find the shape, rank and size of the tensors you created in 1.

In [143]:
print(tens01.shape)
print(tens01.ndim)
print(tf.rank(tens01))
print(tf.size(tens01))


(2, 3)
2
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [144]:
tf.random.set_seed(42)
tens02 = tf.random.uniform(shape=(5,300))
tens03 = tf.random.uniform(shape=(5,300))

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [145]:
# tens05 = tf.linalg.matmul(tens02, tens03) dimension mismatch
tens05 = tf.linalg.matmul(tens02, tf.transpose(tens03))

5. Multiply the two tensors you created in 3 using dot product

In [146]:
tens06 = tf.tensordot(tens02, tens03, axes=0)

In [147]:
#tens07 = tf.tensordot(tens02, tens03, axes =1 ) dimension mismatch

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [148]:
tf.random.set_seed(42)
tens08 = tf.random.uniform((224,224,3))

7. Find the min and max values of the tensor you created in 6.

In [149]:
print(tf.reduce_max(tens08))
print(tf.reduce_min(tens08))

tf.Tensor(0.999998, shape=(), dtype=float32)
tf.Tensor(3.5762787e-07, shape=(), dtype=float32)


8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [150]:
tens09 = tf.expand_dims(tens08, axis=0)
print(tens09.shape)
tens09 = tf.squeeze(tens09)
print(tens09.shape)

(1, 224, 224, 3)
(224, 224, 3)


9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [151]:
tf.random.set_seed(22)

tens10 = tf.random.uniform(shape=[10], minval =1, maxval = 7, dtype = tf.int32)
print(tens10)
print(tens10.shape)
print(tf.argmax(tens10))
print(tf.argmin(tens10))

tf.Tensor([1 3 4 4 1 4 2 1 5 5], shape=(10,), dtype=int32)
(10,)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


10. One-hot encode the tensor you created in 9

In [152]:
tens11 = tf.one_hot(tens10, depth = tf.reduce_max(tens10), on_value='hello', off_value='world ')
tens11

<tf.Tensor: shape=(10, 5), dtype=string, numpy=
array([[b'world ', b'hello', b'world ', b'world ', b'world '],
       [b'world ', b'world ', b'world ', b'hello', b'world '],
       [b'world ', b'world ', b'world ', b'world ', b'hello'],
       [b'world ', b'world ', b'world ', b'world ', b'hello'],
       [b'world ', b'hello', b'world ', b'world ', b'world '],
       [b'world ', b'world ', b'world ', b'world ', b'hello'],
       [b'world ', b'world ', b'hello', b'world ', b'world '],
       [b'world ', b'hello', b'world ', b'world ', b'world '],
       [b'world ', b'world ', b'world ', b'world ', b'world '],
       [b'world ', b'world ', b'world ', b'world ', b'world ']],
      dtype=object)>

In [222]:
a_tensor = tf.constant([
    [
        [1,2,3],[4,5,6],[7,8,9],
        [9,8,7],[6,5,4],[3,2,1]
    ],
    [
        [10,20,30],[40,50,60],[70,80,90],
        [90,80,70],[60,50,40],[30,20,10]
    ],
    [
        [-1,-2,-3],[-4,-5,-6],[-7,-8,-9],
        [-9,-8,-7],[-6,-5,-4],[-3,-2,-1]
    ],
    [
        [-10,-20,-30],[-40,-50,-60],[-70,-80,-90],
        [-90,-80,-70],[-60,-50,-40],[-30,-20,-10]
    ]
    
])
a_tensor

<tf.Tensor: shape=(4, 6, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [  9,   8,   7],
        [  6,   5,   4],
        [  3,   2,   1]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [ 90,  80,  70],
        [ 60,  50,  40],
        [ 30,  20,  10]],

       [[ -1,  -2,  -3],
        [ -4,  -5,  -6],
        [ -7,  -8,  -9],
        [ -9,  -8,  -7],
        [ -6,  -5,  -4],
        [ -3,  -2,  -1]],

       [[-10, -20, -30],
        [-40, -50, -60],
        [-70, -80, -90],
        [-90, -80, -70],
        [-60, -50, -40],
        [-30, -20, -10]]])>

In [228]:
print('sum across the most inner dimension: 6 = sum([1,2,3]), 15 = sum([4,5,6]) and so on.')
tf.reduce_sum(a_tensor, axis=2)

sum across the most inner dimension: 6 = sum([1,2,3]), 15 = sum([4,5,6]) and so on


<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[   6,   15,   24,   24,   15,    6],
       [  60,  150,  240,  240,  150,   60],
       [  -6,  -15,  -24,  -24,  -15,   -6],
       [ -60, -150, -240, -240, -150,  -60]])>

In [229]:
print('sum across the middle dimension: 30 = sum([1, 4, 7, 9, 6, 3]),and so on ')
tf.reduce_sum(a_tensor, axis=1)


sum across the most inner dimension: 6 = sum([1,2,3]), 15 = sum([4,5,6]) and so on


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  30,   30,   30],
       [ 300,  300,  300],
       [ -30,  -30,  -30],
       [-300, -300, -300]])>

In [232]:
print('sum across the outer dimension: 0 = sum([[1, 10, -1 , -10]),and so on ')
tf.reduce_sum(a_tensor, axis=0)


sum across the outer dimension: 0 = sum([[1, 10, -1 , -10]),and so on 


<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [233]:
print('the first entry of every element of the outer dimension (axis=0) ')
a_tensor[:,:1,:1]

<tf.Tensor: shape=(4, 1, 1), dtype=int32, numpy=
array([[[  1]],

       [[ 10]],

       [[ -1]],

       [[-10]]])>

In [234]:
print('the first entry of every element of the middle dimension (axis=1) ')
a_tensor[:1,:,:1]

the first entry of every element of the middle dimension (axis=1) 


<tf.Tensor: shape=(1, 6, 1), dtype=int32, numpy=
array([[[1],
        [4],
        [7],
        [9],
        [6],
        [3]]])>

In [235]:
print('the first entry of every element of the inner dimension (axis=2) ')
a_tensor[:1,:1,:]

the first entry of every element of the inner dimension (axis=2) 


<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]])>